name: ActinEigo
favicon: null
layout_spectrum: 0.4558
typography_spectrum: 0.31640458991751075
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.6339723635464907
  lightness: 0.6616416710894555
  saturation: 0.25783986155875027
  rhythmicContrast: 0.47112719202414155
purpose: []
